pipeline:
  _target_: qa.QA_Pipeline
  model: ixa-ehu/SciBERT-SQuAD-QuAC
  device: cpu
  topk: 1

hf_bert:
  _target_: qa.QA_HF
  model: ixa-ehu/SciBERT-SQuAD-QuAC
  batch_size: 5
  device: cpu
  n_best: 1